title: Jornal_MED
email: contato@jornal-med.com
description: >-
  Jornal_MED: Notícias e informações atualizadas sobre política, saúde, economia e tecnologia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Equipe Jornal_MED
featured_post: 2024-04-27-destaque-principal

# Configurações de build
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
sass:
  sass_dir: _sass
  style: compressed

# Coleções para seções
collections:
  sections:
    output: true

# Configurações de plugins
plugins:
  - jekyll-feed

# Exclusões
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
